# Generated by Django 4.1.7 on 2023-03-02 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_directory_parent_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='sharing_dirs', to=settings.AUTH_USER_MODEL, verbose_name='Общие директории'),
        ),
        migrations.AddField(
            model_name='file',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='sharing_files', to=settings.AUTH_USER_MODEL, verbose_name='Общие файлы'),
        ),
    ]
